### ISSUE TITLE
Terminal text selection is invisible

### ISSUE THREAD

**Issue by barneycarroll** [mubartok/minuit-vscode-theme#2]
Minuit doesn't distinguish highlighted text in the terminal, which is a huge usability issue. I'd been spending ages trying to figure out which of my extensions were disabling mouse selection in the terminal – after a while of disabling and iteratively re-enabling I discovered it was Minuit theme which simply wasn't reflecting the selection visually! 😅

_Unrelated to issue: I am such a massive fan of this theme – I've spent years experimenting with low-contrast light-on-dark themes that don't introduce such unnecessarily noisily distinctions between different language token types. I'd had some OK experience with even lower-distinction themes but recently I've been using a lot of nested language code (SQL/CSS-in-JS via [`es6-string-html` and others](https://marketplace.visualstudio.com/items?itemName=Tobermory.es6-string-html), and Minuits at-a-glance colour differentiation between those languages is invaluable. Love the work, thank you!_

**Comment by michaelabrt** [comment]
Hey, thanks a lot for the "Unrelated to issue" part 😉 I'm glad you like the theme! Thanks for fixing this issue as well and sorry it caused you so much trouble haha I never realized this since I don't use VSCode built-in terminal. I just merged your PR and I'll publish the patched version tonight. Have a good one!
